# Generated by Django 5.0.1 on 2024-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Ladies'), ('ML', 'Gents'), ('LS', 'Kids'), ('MS', 'Watchs'), ('GH', 'Perfumes'), ('CZ', 'Cosmatics')], max_length=2),
        ),
    ]
